version: '3.8'

services:
  
  auth_api:
    build:
      context: .
      dockerfile: Dockerfile.python  
    container_name: auth_fastapi_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app  
    restart: always

  image_service:
    build:
      context: .
      dockerfile: Dockerfile_go      
    container_name: image_go_container
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads      
    restart: always